name: Label PRs by Branch

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-branch-labeler-action@v3
        with:
          configuration-path: .github/pr-branch-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
